Using model : mzysml
 * Serving Flask app "serve_model" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
2020-12-04 01:15:10,370 - werkzeug - INFO -  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2020-12-04 01:15:10,399 - werkzeug - INFO -  * Restarting with inotify reloader
2020-12-04 01:15:12,611 - werkzeug - WARNING -  * Debugger is active!
2020-12-04 01:15:12,612 - werkzeug - INFO -  * Debugger PIN: 179-745-706
2020-12-04 01:15:23,605 - werkzeug - INFO - 127.0.0.1 - - [04/Dec/2020 01:15:23] "[37mPOST /api/ HTTP/1.1[0m" 200 -
Using model : mzysml
 * Serving Flask app "serve_model" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
Traceback (most recent call last):
  File "src/models/serve_model.py", line 56, in <module>
    app.run(debug=True, host="0.0.0.0", port=port)
  File "/home/sfartit/.local/lib/python3.8/site-packages/flask/app.py", line 990, in run
    run_simple(host, port, self, **options)
  File "/home/sfartit/.local/lib/python3.8/site-packages/werkzeug/serving.py", line 1030, in run_simple
    s.bind(server_address)
OSError: [Errno 98] Address already in use
2020-12-04 03:02:07,198 - werkzeug - INFO - 127.0.0.1 - - [04/Dec/2020 03:02:07] "[37mPOST /api/ HTTP/1.1[0m" 200 -
Using model : mzysml
 * Serving Flask app "serve_model" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
Traceback (most recent call last):
  File "src/models/serve_model.py", line 56, in <module>
    app.run(debug=True, host="0.0.0.0", port=port)
  File "/home/sfartit/.local/lib/python3.8/site-packages/flask/app.py", line 990, in run
    run_simple(host, port, self, **options)
  File "/home/sfartit/.local/lib/python3.8/site-packages/werkzeug/serving.py", line 1030, in run_simple
    s.bind(server_address)
OSError: [Errno 98] Address already in use
2020-12-04 03:02:46,750 - werkzeug - INFO - 127.0.0.1 - - [04/Dec/2020 03:02:46] "[37mPOST /api/ HTTP/1.1[0m" 200 -
2020-12-05 01:57:05,782 - werkzeug - INFO - 127.0.0.1 - - [05/Dec/2020 01:57:05] "[33mGET / HTTP/1.1[0m" 404 -
2020-12-05 01:57:06,141 - werkzeug - INFO - 127.0.0.1 - - [05/Dec/2020 01:57:06] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
2020-12-05 01:58:36,136 - werkzeug - INFO - 127.0.0.1 - - [05/Dec/2020 01:58:36] "[37mPOST /api/ HTTP/1.1[0m" 200 -
2020-12-05 01:59:14,029 - werkzeug - INFO - 127.0.0.1 - - [05/Dec/2020 01:59:14] "[37mPOST /api/ HTTP/1.1[0m" 200 -
2020-12-05 01:59:31,148 - werkzeug - INFO - 127.0.0.1 - - [05/Dec/2020 01:59:31] "[37mPOST /api/ HTTP/1.1[0m" 200 -
2020-12-05 02:00:33,503 - werkzeug - INFO - 127.0.0.1 - - [05/Dec/2020 02:00:33] "[37mPOST /api/ HTTP/1.1[0m" 200 -
2020-12-05 22:30:16,628 - werkzeug - INFO - 127.0.0.1 - - [05/Dec/2020 22:30:16] "[37mPOST /api/ HTTP/1.1[0m" 200 -
2020-12-06 02:19:37,962 - werkzeug - INFO - 127.0.0.1 - - [06/Dec/2020 02:19:37] "[37mPOST /api/ HTTP/1.1[0m" 200 -
2020-12-06 02:27:33,592 - werkzeug - INFO - 127.0.0.1 - - [06/Dec/2020 02:27:33] "[37mPOST /api/ HTTP/1.1[0m" 200 -
2020-12-06 02:28:09,941 - werkzeug - INFO - 127.0.0.1 - - [06/Dec/2020 02:28:09] "[37mPOST /api/ HTTP/1.1[0m" 200 -
